version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: gamecenter-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: game-center
      TZ: Asia/Taipei
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:7.2
    container_name: gamecenter-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
